tfteamaker/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

tfteamaker/main/routes.py
from flask import Blueprint, request, render_template

from tfteamaker.models import Post

main = Blueprint('main', __name__)


@main.route('/')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=3)
    return render_template('home.html', page_title="Home", posts=posts)


@main.route('/about')
def about():
    return render_template('about.html', page_title="About")

tfteamaker/posts/routes.py
from flask import Blueprint, flash, redirect, render_template, url_for, request, abort
from flask_login import login_required, current_user

from tfteamaker import db
from tfteamaker.models import Post
from tfteamaker.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        flash('Your post has been created', category='success')
        post = Post(title=form.title.data, content=form.content.data, author_id=current_user.id)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New post')


@posts.route('/post/<int:post_id>')
def post(post_id):
    # post = Post.query.get(post_id)
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

@login_required
@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author_id != current_user.id:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has beed updated!', category='success')
        return redirect(url_for('posts.post', post_id=post_id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update post')


@login_required
@posts.route('/post/<int:post_id>/delete', methods=['POST'])
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    post_title_to_delete = post.title
    if post.author_id != current_user.id:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash(f'Your post {post_title_to_delete} has beed deleted.', category='success')
    return redirect(url_for('main.home'))

tfteamaker/teams/routes.py
from flask import Blueprint, redirect, flash, url_for, render_template, request, jsonify
from flask_restful import Resource
from .forms import UnitForm
from tfteamaker.models import Unit
from tfteamaker import db
from flask_cors import cross_origin

from .cors_bypass import _build_cors_prelight_response, _corsify_actual_response

teams = Blueprint('teams', __name__)


@teams.route('/new_team')
def new_team():
    units = Unit.query.all()
    return render_template('new_team.html', title='New Team', units=units)


class CompSerializer:
    def __init__(self, units):
        self.units = units

        # to bedzie zwracac funkcja serializer, dalem to tutaj zeby sie latwiej przepisywalo klasy
        r_dict = {"units": self.units,
                  "synergies": {

                  }}

        self.soulbound = set()
        self.warden = set()
        self.summoner = set()
        self.ranger = set()
        self.predator = set()
        self.blademaster = set()
        self.mage = set()
        self.mystic = set()
        self.berserker = set()
        self.druid = set()
        self.assassin = set()
        self.alchemist = set()

        self.light = set()
        self.crystal = set()
        self.glacial = set()
        self.electric = set()
        self.inferno = set()
        self.desert = set()
        self. cloud = set()
        self.poison = set()
        self.lunar = set()
        self.shadow = set()
        self.steel = set()
        self.variable = set()
        self.woodland = set()
        self.ocean = set()
        self.mountain = set()

    def serialize(self):
        units_ = []
        for unit in self.units:
            u = Unit.query.filter_by(name=unit).first()
            units_.append(u)

        instance_dict = self.__dict__.items()
        for class_, set_ in instance_dict:
            for unit in units_:
                if unit.class1 == class_:
                    set_.add(unit)
                if unit.class2 == class_:
                    set_.add(unit)
                if unit.class3 == class_:
                    set_.add(unit)

        r_dict = {}
        for class_, set_ in instance_dict:
            if class_ != 'units':
                if len(set_) != 0:
                    r_dict[class_] = {}
                    units = {'units': []}
                    for unit in set_:
                        units['units'].append(str(unit))
                    r_dict[class_] = units
        return r_dict


@teams.route('/api/new_team', methods=["POST", "OPTIONS"])
def comp():
    if request.method == "OPTIONS":
        return _build_cors_prelight_response()
    if request.method == "POST":
        json_data = request.get_json()
        cs = CompSerializer(json_data.get('units'))
        r_dict = cs.serialize()
        response = jsonify(r_dict)
        return _corsify_actual_response(response)
























# @teams.route('/new_unit', methods=['GET', 'POST'])
# def new_unit():
#     form = UnitForm()
#     if form.validate_on_submit():
#         unit = Unit(name=form.name.data.capitalize(), cost=form.cost.data, clean_name=form.name.data.lower(), class1=form.class1.data, class2=form.class2.data, class3=form.class3.data)
#         db.session.add(unit)
#         db.session.commit()
#         flash(f'Created unit name={unit.name}, cost={form.cost.data}, clean_name={unit.clean_name}, class1={form.class1.data}, class2={form.class2.data}, class3={form.class3.data})', category='warning')
#         return redirect(url_for('teams.new_unit'))
#     return render_template('new_unit.html', form=form)

tfteamaker/users/routes.py
from flask import Blueprint, redirect, flash, url_for, render_template, request
from flask_login import current_user, login_user, logout_user, login_required

from tfteamaker import bcrypt, db
from tfteamaker.models import User, Post
from tfteamaker.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from tfteamaker.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        # decode so that it's not a bytestring
        hashed_pd = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_pd)
        db.session.add(user)
        db.session.commit()
        flash(message=f'Account created for Tactician {form.username.data}! Let the TeaMaking begin!', category='info')
        login_user(user=user)
        return redirect(url_for('main.home'))
    return render_template('register.html', page_title="Register", form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash(message=f"Welcome back {form.username.data}!", category='success')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Please check username and password.', category='danger')
    return render_template('login.html', page_title="Login", form=form)


@users.route('/logout')
def logout():
    logout_user()
    flash(message="Logged out, see you soon.", category='success')
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been updated.", category='success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename=f'profile_pics/{current_user.image_file}')
    return render_template('account.html', page_title="Account",
                           image_file=image_file, form=form)


@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=3)
    return render_template('user_posts.html', page_title=f"{user.username} posts", posts=posts, user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has beed sent with instructions to reset your password', category='info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Invalid or expired token', category='warning')
        return redirect(url_for('users.reset_token'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        # decode so that it's not a bytestring
        hashed_pd = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_pd
        db.session.commit()
        flash(message=f'Your password has been updated', category='success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

tfteamaker/templates/about.html
{% extends 'layout.html' %}
{% block content %}
    <h1>What is this?</h1>
    <p>Hello, my name is Dominik and what you're seeing right now is a project I decided to create in my spare time.</p>
    <p>The idea was to build an intuitive website used for creating Teamfight Tactics teamcomps and easily share them
        with friends. I highly encourage you to sign up, use it and help me improve this WebApp.</p>
    <p>Technologies I used were:</p>
    <ul>
        <li>Flask - for serverside operations</li>
        <li>HTML/CSS/JS - for client side operations</li>
    </ul>
{% endblock %}

tfteamaker/templates/account.html
{% extends 'layout.html' %}
{% block content %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ image_file }}">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
        <button class="btn btn-warning mb" data-toggle="collapse" data-target="#collapseForm">
            Account Info
        </button>
        <div class="collapse mt-3" id="collapseForm">
            <form method="POST" action="" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <div class="form-group">
                        {{ form.username.label(class="form-control-label") }}

                        {% if form.username.errors %}
                            {{ form.username(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>

                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    <br>
                    {{ form.picture(class='form-controle-file') }}
                    {% if form.picture.errors %}
                        {% for error in errors %}
                            <span class="text-danger">{{ error }}</span>
                        {% endfor %}
                    {% endif %}
                </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>
        </div>
    </div>
{% endblock %}

tfteamaker/templates/base_for_new_team.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap css -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/new_team.css') }}">


    <script
            src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <script
            src="https://cdnjs.cloudflare.com/ajax/libs/jquery-json/2.6.0/jquery.json.min.js"
    ></script>

    {% if page_title %}
        <title>TFTeaMaker | {{ page_title }}</title>
    {% else %}
        <title>TFTeaMaker</title>
    {% endif %}

    <script src="https://kit.fontawesome.com/f0e1fe1e4d.js" crossorigin="anonymous"></script>
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-3" href="/">TFTeaMaker</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{{ url_for('teams.new_team') }}">New Team</a>
                    <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Log out</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>

<main role="main" class="container">
    <!-- Flash messeges -->
    {% with messages = get_flashed_messages(with_categories=True) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
</main>

<!-- Footer -->
<footer class="footer page-footer">
    <div class="text-center py-3">© 2020 Built by:
        <a href="https://www.github.com/wieloryb331"><i class="fab fa-github"></i></a>
        <a href="https://www.instagram.com/pudelkociastek/"><i class="fab fa-instagram"></i></a>
    </div>
</footer>

<!-- Bootstrap js -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

</body>
</html>

tfteamaker/templates/home.html
{% extends 'layout.html' %}

{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
            <img src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" alt=""
                 class="rounded-circle article-img">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username)}}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%d/%m/%Y %H:%M') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page==page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num ) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num ) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}

    {% endfor %}

{% endblock %}

tfteamaker/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap css -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">

    {% if page_title %}
        <title>TFTeaMaker | {{ page_title }}</title>
    {% else %}
        <title>TFTeaMaker</title>
    {% endif %}

    <script src="https://kit.fontawesome.com/f0e1fe1e4d.js" crossorigin="anonymous"></script>

</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-3" href="/">TFTeaMaker</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{{ url_for('teams.new_team') }}">New Team</a>
                    <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Log out</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>

<main role="main" class="container">
    <div class="row">
        <div class="col-md-8">
            <!-- Flash messeges -->
            {% with messages = get_flashed_messages(with_categories=True) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
            <div class="content-section">
                <h3>Our Sidebar</h3>
                <p class='text-muted'>You can put any information here you'd like.
                <ul class="list-group">
                    <li class="list-group-item list-group-item-light">Latest Posts</li>
                    <li class="list-group-item list-group-item-light">Announcements</li>
                    <li class="list-group-item list-group-item-light">Calendars</li>
                    <li class="list-group-item list-group-item-light">etc</li>
                </ul>
                </p>
            </div>
        </div>
    </div>
</main>

<!-- Footer -->
<footer class="footer page-footer">
    <div class="text-center py-3">© 2020 Built by:
        <a href="https://www.github.com/wieloryb331"><i class="fab fa-github"></i></a>
        <a href="https://www.instagram.com/pudelkociastek/"><i class="fab fa-instagram"></i></a>
    </div>
</footer>

<!-- Bootstrap js -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

tfteamaker/templates/login.html
{% extends 'layout.html' %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>

                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class='form-check-input') }}
                    {{ form.remember.label(class='form-check-label') }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">Forgot password?</a>
            </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Don't have an account yet? <a class="ml-2" href="{{ url_for('users.register') }}">Register</a>
        </small>
    </div>
{% endblock %}

tfteamaker/templates/post.html
{% extends 'layout.html' %}

{% block content %}
    <article class="media content-section">
        <img src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" alt=""
             class="rounded-circle article-img">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                <small class="text-muted">{{ post.date_posted.strftime('%d-%m-%Y') }}</small>
                {% if post.author == current_user %}
                    <div>
                        <a href="{{ url_for('posts.update_post', post_id=post.id) }}"
                           class="btn btn-secondary btn-sm mt-1 mb-1">Update</a>
                        <button class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">
                            Delete
                        </button>
                    </div>
                {% endif %}
            </div>
            <h2>{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
        </div>
    </article>


    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Do you want to delete post "{{ post.title }}"?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

tfteamaker/templates/user_posts.html
{% extends 'layout.html' %}

{% block content %}
    <h1 class="mb-3">Teams by {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
        <article class="media content-section">
            <img src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" alt=""
                 class="rounded-circle article-img">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%d/%m/%Y %H:%M') }}</small>
                </div>
                <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
                <p class="article-content">{{ post.content }}</p>
            </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page==page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num ) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num ) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}

    {% endfor %}

{% endblock %}